In [1]:
import pandas as pd
import numpy as np
import importlib 
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
data = pd.read_csv("database.csv")
del data['article_id']
del data['state']

In [5]:
data

,full_name,sex,birth_year,city,country,continent,latitude,longitude,occupation,industry,domain,article_languages,page_views,average_views,historical_popularity_index
0,Aristotle,Male,-384,Stageira,Greece,Europe,40.33333,23.50000,Philosopher,Philosophy,Humanities,152,56355172,370758,31.9938
1,Plato,Male,-427,Athens,Greece,Europe,37.96667,23.71667,Philosopher,Philosophy,Humanities,142,46812003,329662,31.9888
2,Jesus Christ,Male,-4,Judea,Israel,Asia,32.50000,34.90000,Religious Figure,Religion,Institutions,214,60299092,281771,31.8981
3,Socrates,Male,-469,Athens,Greece,Europe,37.96667,23.71667,Philosopher,Philosophy,Humanities,137,40307143,294213,31.6521
4,Alexander the Great,Male,-356,Pella,Greece,Europe,40.80000,22.51667,Military Personnel,Military,Institutions,138,48358148,350421,31.5840
5,Leonardo da Vinci,Male,1452,Vinci,Italy,Europe,43.78333,10.91667,Inventor,Invention,Science & Technology,174,88931135,511098,31.4644
6,Confucius,Male,-551,Qufu,China,Asia,NaN,NaN,Philosopher,Philosophy,Humanities,192,22363652,116477,31.3705
7,Julius Caesar,Male,-100,Rome,Italy,Europe,41.90000,12.50000,Politician,Government,Institutions,128,43088745,336631,31.1161
8,Homer,Male,-800,Smyrna,Turkey,Europe,38.41861,27.13917,Writer,Language,Humanities,141,20839405,147797,31.1087
9,Pythagoras,Male,-570,Samos Island,Greece,Europe,37.75000,26.83333,Philosopher,Philosophy,Humanities,114,26168219,229546,31.0691
10,Archimedes,Male,-287,Syracuse,Italy,Europe,37.08333,15.28333,Mathematician,Math,Science & Technology,129,22022077,170714,30.9907
11,Moses,Male,-1391,Wadi Tumilat,Egypt,Africa,NaN,NaN,Religious Figure,Religion,Institutions,115,21880195,190263,30.8632
12,Muhammad,Male,570,Mecca,Saudi Arabia,Asia,21.41667,39.81667,Religious Figure,Religion,Institutions,150,43026648,286844,30.6500
13,Abraham,Male,-1800,Other,Unknown,NaN,33.70000,43.50000,Religious Figure,Religion,Institutions,105,17824676,169759,30.6047
14,Adolf Hitler,Male,1889,Braunau am Inn,Austria,Europe,48.25833,13.03500,Politician,Government,Institutions,169,128368798,759579,30.5778
15,Wolfgang Amadeus Mozart,Male,1756,Salzburg,Austria,Europe,47.80000,13.03333,Composer,Music,Arts,177,51363334,290188,30.5146
16,Charlemagne,Male,742,Liège,Belgium,Europe,NaN,NaN,Politician,Government,Institutions,116,26626252,229537,30.4837
17,William Shakespeare,Male,1564,Stratford-upon-Avon,United Kingdom,Europe,52.19000,-1.71000,Writer,Language,Humanities,163,74882297,459401,30.4398
18,Michelangelo,Male,1475,Caprese Michelangelo,Italy,Europe,43.63333,11.98333,Painter,Fine Arts,Arts,158,39992803,253119,30.4383
19,Augustus,Male,-63,Rome,Italy,Europe,41.90000,12.50000,Politician,Government,Institutions,117,20307663,173570,30.4195
20,Napoleon Bonaparte,Male,1769,Corsica,France,Europe,41.92670,8.73690,Politician,Government,Institutions,145,57559307,396961,30.3263
21,Isaac Newton,Male,1642,Woolsthorpe-by-Colsterworth,United Kingdom,Europe,52.80986,-0.62877,Physicist,Natural Sciences,Science & Technology,191,59909049,313660,30.2889
22,Albert Einstein,Male,1879,Ulm,Germany,Europe,48.40000,9.98333,Physicist,Natural Sciences,Science & Technology,166,89771090,540790,30.2106
23,Christopher Columbus,Male,1451,Genoa,Italy,Europe,44.41111,8.93278,Explorer,Explorers,Exploration,153,58442090,381974,30.1753
24,Johann Sebastian Bach,Male,1685,Eisenach,Germany,Europe,50.97611,10.32056,Composer,Music,Arts,144,29753654,206623,30.1672
25,Dante Alighieri,Male,1265,Florence,Italy,Europe,43.78333,11.25000,Writer,Language,Humanities,137,20540747,149932,30.1496
26,Ludwig van Beethoven,Male,1770,Bonn,Germany,Europe,50.73399,7.09981,Composer,Music,Arts,153,48132344,314590,30.1093
27,Gautama Buddha,Male,-563,Lumbini,Nepal,Asia,27.53333,83.05000,Philosopher,Philosophy,Humanities,124,23685332,191011,30.0418
28,Cleopatra VII of Egypt,Female,-69,Alexandria,Egypt,Africa,31.20000,29.91667,Politician,Government,Institutions,100,18849501,188495,30.0367
29,Martin Luther,Male,1483,Eisleben,Germany,Europe,51.51667,11.55000,Religious Figure,Religion,Institutions,125,35167994,281344,30.0311
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11311,Itumeleng Khune,Male,1987,Ventersdorp,South Africa,Africa,-26.31667,26.81667,Soccer Player,Team Sports,Sports,27,320092,11855,12.4219
11312,Benjamin Angus Wright,Male,1950,England,United Kingdom,Europe,NaN,NaN,Composer,Music,Arts,40,1965,49,12.3932
11313,Kevin Anderson,Male,1986,Johannesburg,South Africa,Africa,-26.20444,28.04556,Tennis Player,Individual Sports,Sports,27,62343,2309,12.3807
11314,Shane Dawson,Male,1988,Los Angeles,United States,North America,33.76833,-118.19556,Actor,Film And Theatre,Arts,27,2247314,83234,12.3796
11315,Asa,Male,Unknown,Other,Unknown,Unknown,NaN,NaN,Politician,Government,Institutions,31,282386,9109,12.3371
11316,Greg Cipes,Male,1980,Coral Springs,United States,North America,26.27056,-80.25917,Actor,Film And Theatre,Arts,27,764235,28305,12.3083
11317,Bilawal Bhutto Zardari,Male,1988,Karachi,Pakistan,Asia,24.86000,67.01000,Politician,Government,Institutions,30,841239,28041,12.2677
11318,Eldar Gasimov,Male,1989,Baku,Azerbaijan,Asia,40.39528,49.88222,Singer,Music,Arts,28,402049,14359,12.2422
11319,Addys D'Mercedes,Female,1985,Moa,Cuba,North America,20.63972,-74.91750,Singer,Music,Arts,31,27958,902,12.2018
11320,Ivi Adamou,Female,1993,Ayia Napa,Cyprus,Asia,34.98000,34.00000,Singer,Music,Arts,30,558856,18629,12.1482
11321,Leisel Jones,Female,1985,Katherine,Australia,Oceania,-14.46667,132.26667,Swimmer,Individual Sports,Sports,26,463947,17844,12.1441
11322,Malala Yousafzai,Female,1998,Mingora,Pakistan,Asia,34.78333,72.36667,Social Activist,Activism,Public Figure,41,4667416,113839,12.1429
11323,Infanta Leonor of Spain,Female,2005,Madrid,Spain,Europe,40.40000,-3.68333,Nobleman,Government,Institutions,28,1307619,46701,12.1348
11324,Shelly-Ann Fraser,Female,1986,Kingston,Jamaica,North America,17.98333,-76.80000,Athlete,Individual Sports,Sports,30,733320,24444,12.1316
11325,Soluna Samay,Female,1990,Guatemala City,Guatemala,North America,14.61333,-90.53528,Singer,Music,Arts,32,228780,7149,12.0464
11326,Anton Shunin,Male,1987,Moscow,Russia,Europe,55.75000,37.61667,Soccer Player,Team Sports,Sports,26,117406,4516,12.0357
11327,Emmanuel Frimpong,Male,1992,Kumasi,Ghana,Africa,6.66667,-1.61667,Soccer Player,Team Sports,Sports,26,1569708,60373,12.0223
11328,Mohamed Farah,Male,1983,Mogadishu,Somalia,Africa,2.03333,45.35000,Athlete,Individual Sports,Sports,28,2790213,99650,11.9302
11329,Stephanie Rice,Female,1988,Brisbane,Australia,Oceania,-27.46667,153.03333,Swimmer,Individual Sports,Sports,31,1552820,50091,11.8106
11330,Václav Pilař,Male,1988,Chlumec nad Cidlinou,Czech Republic,Europe,50.15556,15.45778,Soccer Player,Team Sports,Sports,34,319330,9392,11.7884
11331,Marc Albrighton,Male,1989,Tamworth,United Kingdom,Europe,52.63300,-1.69500,Soccer Player,Team Sports,Sports,26,495420,19055,11.7258
11332,Shane Long,Male,1987,Gortnahoe,Ireland,Europe,NaN,NaN,Soccer Player,Team Sports,Sports,26,799202,30739,11.7174
11333,Sun Yang,Male,1991,Hangzhou,China,Asia,30.25000,120.16667,Swimmer,Individual Sports,Sports,26,491910,18920,11.6234
11334,Rebecca Soni,Female,1987,Freehold Borough,United States,North America,40.26022,-74.27588,Swimmer,Individual Sports,Sports,27,886815,32845,11.4050
11335,Jetro Willems,Male,1994,Rotterdam,Netherlands,Europe,51.91667,4.50000,Soccer Player,Team Sports,Sports,27,577913,21404,11.3956
11336,Sean St Ledger,Male,1984,Solihull,United Kingdom,Europe,52.41290,-1.77209,Soccer Player,Team Sports,Sports,28,380965,13606,11.1346
11337,Saina Nehwal,Female,1990,Hisar,India,Asia,29.16670,75.71670,Athlete,Individual Sports,Sports,26,2255010,86731,10.6122
11338,Rūta Meilutytė,Female,1997,Kaunas,Lithuania,Europe,54.90000,23.88611,Swimmer,Individual Sports,Sports,32,342719,10710,10.3821
11339,Vladimír Weiss,Male,1989,Bratislava,Slovakia,Europe,48.14389,17.10972,Soccer Player,Team Sports,Sports,27,12479,462,10.2495
11340,Missy Franklin,Female,1995,Los Angeles,United States,North America,34.15611,-118.13194,Swimmer,Individual Sports,Sports,26,1894716,72874,9.8794

In [ ]:
class MarkovChain:
    def __init__(self):
        pass